const SET_BOARD_STATE = 'SET_BOARD_STATE'

/* Ticket actions */
const CREATE_TICKET = 'CREATE_TICKET'
const AUTO_CLOSE_TICKET = 'AUTO_CLOSE_TICKET'
const UPDATE_TICKET_STATUS = 'UPDATE_TICKET_STATUS'

const EDIT_TICKET_DETAILS_INIT = 'EDIT_TICKET_DETAILS_INIT'

const UPDATE_EDIT_TICKET_FORM_DATA = 'UPDATE_EDIT_TICKET_FORM_DATA'

export {
	SET_BOARD_STATE,
	UPDATE_TICKET_STATUS,
	AUTO_CLOSE_TICKET,
	CREATE_TICKET,
	EDIT_TICKET_DETAILS_INIT,
	UPDATE_EDIT_TICKET_FORM_DATA
}
