const SET_BOARD_STATE = 'SET_BOARD_STATE'

/* Ticket actions */
const AUTO_CLOSE_TICKET = 'AUTO_CLOSE_TICKET'
const UPDATE_TICKET_STATUS = 'UPDATE_TICKET_STATUS'
const UPDATE_TICKET_TIMERS = 'UPDATE_TICKET_TIMERS'

const EDIT_TICKET_DETAILS_INIT = 'EDIT_TICKET_DETAILS_INIT'

const ADD_NEW_TICKET = 'ADD_NEW_TICKET'
const EDIT_TICKET_DETAILS = 'EDIT_TICKET_DETAILS'
const TICKET_EDITOR_CLOSED = 'TICKET_EDITOR_CLOSED'

const UPDATE_EDIT_TICKET_FORM_DATA = 'UPDATE_EDIT_TICKET_FORM_DATA'

export {
	SET_BOARD_STATE,
	UPDATE_TICKET_STATUS,
	UPDATE_TICKET_TIMERS,
	AUTO_CLOSE_TICKET,
	ADD_NEW_TICKET,
	EDIT_TICKET_DETAILS,
	EDIT_TICKET_DETAILS_INIT,
	TICKET_EDITOR_CLOSED,
	UPDATE_EDIT_TICKET_FORM_DATA
}
